Fix issue of tf.math.real with numeric input
This fix tries to address the issue raised in 30029 where
numeric input does not work with tf.math.real:
```
>>> import tensorflow as tf
>>> tf.math.real(1.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/math_ops.py", line 525, in real
    if input.dtype.is_complex:
AttributeError: 'float' object has no attribute 'dtype'
```

The reason was that unlike other functions in math_ops.py,
tf.math.real does not try to call ops.convert_to_tensor before processing.
This fix fixes the issue.

This fix fixes 30029.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>