Remove the "/" after path in assertion, as path join used somewhere in windows inserts "\" and breaks assertion.
AssertionError: 'gs://example-bucket/tempfiles\\7e4b3f071dc847cb8dbbe08a699b4cad' does not start with 'gs://example-bucket/tempfiles/'
PiperOrigin-RevId: 289149589
Change-Id: Ib655b737661451956d17a1c25322517c1eca32f4