Fix incorrect default values of tf.sparse.to_dense
This fix tries to address the issue where tf.sparse.to_dense
without specifying default value explicitly leads to TypeError:
```
import tensorflow as tf
sample_string = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=['a', 'b'], dense_shape=[3, 4])
tf.sparse.to_dense( sample_string )
...
TypeError: Expected string passed to parameter 'default_value' of op 'SparseToDense', got 0 of type 'int' instead. Error: Expected string, got 0 of type 'int' instead.
```

The issue was that tf.sparse.to_dense use 0 as the default value
which does not work well with string.

This fix changes from `default_value=0` -> `default_value=None`
and use zeros instead.

It consists of an API change though the change is backward compatible.

This fix fixes 30750

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>