Fix hwloc build for ppc64le
This commit: https://github.com/tensorflow/tensorflow/commit/41df105#diff-6fb2e55075204b47da0460ea2abbc32f
broke the CPU unit test build for ppc64le. The compiler error was:

.../libexternal_Shwloc_Slibhwloc.so: error: undefined reference to 'hwloc_linux_component'
.../libexternal_Shwloc_Slibhwloc.so: error: undefined reference to 'hwloc_linuxio_component'

These methods are defined in topology-linux.c, adding the necessary bazel select statement
so they are built during a ppc64le build.