Fix issue with SparseCategoricalCrossentropy: 'list' object has no attribute 'op'
This fix tries to address the issue raised in 33394 where
usage of SparseCategoricalCrossentropy causes the issue:
```
AttributeError: 'list' object has no attribute 'op'
```
when values are passed directly (not calling ops.convert_to_tensor first).

This fix fixes the issue by performing the ops.convert_to_tensor
on y_true and y_pred, similiar to what are done in other losses.

This fix fixes 33394.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>