Fallback to reduce to process the unknown cardinality case
The reason for this consideration is that len() of infinite list does exist
so there is a risk with python itself:
```
python3
Python 3.7.3 (default, Dec 13 2019, 19:58:14)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def fib():
...     a, b = 0, 1
...     while True:
...         a, b = b, a + b
...         yield a
...
>>> len(fib())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'generator' has no len()
>>> len(list(fib()))
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in fib
KeyboardInterrupt
>>>

```

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>