optimizer_v2: Improve error when called in cross-replica context
When calling `Optimizer.apply_gradients()` in a cross-replica distribution
context (with a non-default distribution strategy),
`distribute_ctx.get_replica_context()` returns None, so it would fail with
the error

    [...]/optimizer_v2.py", line 448, in apply_gradients
        return distribute_ctx.get_replica_context().merge_call(
    AttributeError: 'NoneType' object has no attribute 'merge_call'

This commit changes the error to a `RuntimeError` with a more descriptive
error message (inspired by the error message in the v1 optimizer) guiding
the user how to fix the issue, by either calling the `_distributed_apply()`
function instead or by using `tf.distribute.Strategy.experimental_run_v2`.